### ISSUE TITLE
Enhancement: Convert rotated Points to regular Points

### ISSUE THREAD

**Issue by daniel-rck** [songjiahong/Geo.Library#12]
When calculating with some weather data I came across "rotated Grids":
https://gis.stackexchange.com/questions/10808/manually-transforming-rotated-lat-lon-to-regular-lat-lon

So as I'm already using this lib, it would be really cool having a function like `ConvertToRegular(double lat, double lon, Point rotatedPole)`. I could do it too, just wanted to ask in advance if you would accept this enhancement.

**Comment by songjiahong** [comment]
I didn't know about the rotated grids before. Would this be a very common issue for many people, if yes, it's OK to add it in the lib. Otherwise, it may be better to create a shared function of your own in your project.

In case if we want to add this in this lib, I would suggest to have an rotate grids class (maybe named as `RotatePoint`) and do the conversion in this class.

**Comment by songjiahong** [comment]
Updated the version
